project 'GenQuizitive.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenQuizitive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenQuizitive
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'GenQuizitiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenQuizitiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
