project 'GenQuizitive.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GenQuizitive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenQuizitive
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Invites'
  pod 'Firebase/DynamicLinks'
  pod 'FirebaseUI/Auth', '~> 3.0'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'GoogleSignIn'

  target 'GenQuizitiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenQuizitiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
